In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("mushrooms.csv")
df.head()

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   

  gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [3]:
df.isnull().sum()

class                       0
cap-shape                   0
cap-surface                 0
cap-color                   0
bruises                     0
odor                        0
gill-attachment             0
gill-spacing                0
gill-size                   0
gill-color                  0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   class                     8124 non-null   object
 1   cap-shape                 8124 non-null   object
 2   cap-surface               8124 non-null   object
 3   cap-color                 8124 non-null   object
 4   bruises                   8124 non-null   object
 5   odor                      8124 non-null   object
 6   gill-attachment           8124 non-null   object
 7   gill-spacing              8124 non-null   object
 8   gill-size                 8124 non-null   object
 9   gill-color                8124 non-null   object
 10  stalk-shape               8124 non-null   object
 11  stalk-root                8124 non-null   object
 12  stalk-surface-above-ring  8124 non-null   object
 13  stalk-surface-below-ring  8124 non-null   object
 14  stalk-color-above-ring  

In [5]:
from sklearn.preprocessing import LabelEncoder

In [6]:
le = LabelEncoder()
for column in df.columns:
    df[column]=le.fit_transform(df[column])

In [7]:
df.head()

class  cap-shape  cap-surface  cap-color  bruises  odor  gill-attachment  \
0      1          5            2          4        1     6                1   
1      0          5            2          9        1     0                1   
2      0          0            2          8        1     3                1   
3      1          5            3          8        1     6                1   
4      0          5            2          3        0     5                1   

   gill-spacing  gill-size  gill-color  ...  stalk-surface-below-ring  \
0             0          1           4  ...                         2   
1             0          0           4  ...                         2   
2             0          0           5  ...                         2   
3             0          1           5  ...                         2   
4             1          0           4  ...                         2   

   stalk-color-above-ring  stalk-color-below-ring  veil-type  veil-color  \
0                       7                       7          0           2   
1                       7                       7          0           2   
2                       7                       7          0           2   
3                       7                       7          0           2   
4                       7                       7          0           2   

   ring-number  ring-type  spore-print-color  population  habitat  
0            1          4                  2           3        5  
1            1          4                  3           2        1  
2            1          4                  3           2        3  
3            1          4                  2           3        5  
4            1          0                  3           0        1  

[5 rows x 23 columns]

In [8]:
x = df.drop(columns = 'class')
y = df['class']

In [9]:
from sklearn.decomposition import PCA
pca1 = PCA(n_components = 7)
pca1_fit=pca1.fit_transform(x)

In [10]:
pca1_fit

array([[ 0.22820662, -0.34547209, -1.42442513, ...,  2.08873728,
         2.64591476, -1.03203615],
       [-1.93656097,  4.79691211, -3.51166784, ...,  0.55114392,
        -0.28390932,  2.550317  ],
       [-1.65417317,  2.46436226, -3.88082715, ...,  1.04396495,
        -2.0526079 , -2.19086329],
       ...,
       [-1.86050705,  0.47024368,  1.19021188, ...,  0.3643834 ,
         0.05336833, -2.8437084 ],
       [ 7.29306843, -1.25169255, -1.24197629, ..., -1.59230955,
         0.0438697 , -0.3117056 ],
       [-4.83553281, -3.58375805, -0.11250608, ...,  0.5306639 ,
         1.92326423,  1.3609257 ]])

In [11]:
pca1.explained_variance_ratio_

array([0.33758733, 0.16581098, 0.12285821, 0.06796611, 0.05831173,
       0.05092539, 0.04670841])

In [12]:
sum(pca1.explained_variance_ratio_)

0.8501681635086211

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_train,x_test,y_train,y_test = train_test_split(pca1_fit,y,test_size=0.2,random_state=42)

In [15]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier

In [16]:
lr = LogisticRegression()
lr.fit(x_train,y_train)

knn = KNeighborsClassifier()
knn.fit(x_train,y_train)

svc = SVC()
svc.fit(x_train,y_train)

dt = DecisionTreeClassifier()
dt.fit(x_train,y_train)

rf = RandomForestClassifier()
rf.fit(x_train,y_train)

gb = GradientBoostingClassifier()
gb.fit(x_train,y_train)

GradientBoostingClassifier()

In [17]:
y_pred1 = lr.predict(x_test)
y_pred2 = knn.predict(x_test)
y_pred3 = svc.predict(x_test)
y_pred4 = dt.predict(x_test)
y_pred5 = rf.predict(x_test)
y_pred6 = gb.predict(x_test)

In [18]:
from sklearn.metrics import accuracy_score

In [19]:
print("ACC LR" ,accuracy_score(y_test,y_pred1))
print("ACC knn" ,accuracy_score(y_test,y_pred2))
print("ACC svc" ,accuracy_score(y_test,y_pred3))
print("ACC dt" ,accuracy_score(y_test,y_pred4))
print("ACC rf" ,accuracy_score(y_test,y_pred5))
print("ACC gb" ,accuracy_score(y_test,y_pred6))

ACC LR 0.8344615384615385
ACC knn 0.9833846153846154
ACC svc 0.952
ACC dt 0.9753846153846154
ACC rf 0.9981538461538462
ACC gb 0.9384615384615385


In [20]:
pd.DataFrame({'Models':['LR','knn','svc','dt','rf','gb'],
             'Acc_Score':[accuracy_score(y_test,y_pred1)*100,
                         accuracy_score(y_test,y_pred2)*100,
                         accuracy_score(y_test,y_pred3)*100,
                         accuracy_score(y_test,y_pred4)*100,
                         accuracy_score(y_test,y_pred5)*100,
                         accuracy_score(y_test,y_pred6)*100]})

Models  Acc_Score
0     LR  83.446154
1    knn  98.338462
2    svc  95.200000
3     dt  97.538462
4     rf  99.815385
5     gb  93.846154

In [27]:
rf_model = RandomForestClassifier()
rf_model.fit(pca1_fit,y)

RandomForestClassifier()

In [28]:
import joblib
joblib.dump(rf_model,'Mushroom_prediction')

['Mushroom_prediction']

In [29]:
model = joblib.load('Mushroom_prediction')

In [30]:
p = model.predict(pca1.transform([[5,2,4,1,6,1,0,1,4,0,3,2,2,7,7,0,2,1,4,2,3,5]]))

c:\users\dell\appdata\local\programs\python\python39\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but PCA was fitted with feature names
  warnings.warn(


In [31]:
p

array([1])

In [33]:
if p[0]==1:
    print("Poissonous")
else:
    print("Edible")

Poissonous
