In [3]:
import pandas as pd
import seaborn as sns

In [4]:
#tips_df = pd.read_csv(r"F:\Data Science Projects\Data Cleaning\tips.csv")
tips_df = sns.load_dataset("tips")
tips_df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [3]:
x = pd.set_option("display.max_columns",None)
y = pd.set_option("display.max_rows",None)

In [4]:
tips_df

total_bill    tip     sex smoker   day    time  size
0         16.99   1.01  Female     No   Sun  Dinner     2
1         10.34   1.66    Male     No   Sun  Dinner     3
2         21.01   3.50    Male     No   Sun  Dinner     3
3         23.68   3.31    Male     No   Sun  Dinner     2
4         24.59   3.61  Female     No   Sun  Dinner     4
5         25.29   4.71    Male     No   Sun  Dinner     4
6          8.77   2.00    Male     No   Sun  Dinner     2
7         26.88   3.12    Male     No   Sun  Dinner     4
8         15.04   1.96    Male     No   Sun  Dinner     2
9         14.78   3.23    Male     No   Sun  Dinner     2
10        10.27   1.71    Male     No   Sun  Dinner     2
11        35.26   5.00  Female     No   Sun  Dinner     4
12        15.42   1.57    Male     No   Sun  Dinner     2
13        18.43   3.00    Male     No   Sun  Dinner     4
14        14.83   3.02  Female     No   Sun  Dinner     2
15        21.58   3.92    Male     No   Sun  Dinner     2
16        10.33   1.67  Female     No   Sun  Dinner     3
17        16.29   3.71    Male     No   Sun  Dinner     3
18        16.97   3.50  Female     No   Sun  Dinner     3
19        20.65   3.35    Male     No   Sat  Dinner     3
20        17.92   4.08    Male     No   Sat  Dinner     2
21        20.29   2.75  Female     No   Sat  Dinner     2
22        15.77   2.23  Female     No   Sat  Dinner     2
23        39.42   7.58    Male     No   Sat  Dinner     4
24        19.82   3.18    Male     No   Sat  Dinner     2
25        17.81   2.34    Male     No   Sat  Dinner     4
26        13.37   2.00    Male     No   Sat  Dinner     2
27        12.69   2.00    Male     No   Sat  Dinner     2
28        21.70   4.30    Male     No   Sat  Dinner     2
29        19.65   3.00  Female     No   Sat  Dinner     2
30         9.55   1.45    Male     No   Sat  Dinner     2
31        18.35   2.50    Male     No   Sat  Dinner     4
32        15.06   3.00  Female     No   Sat  Dinner     2
33        20.69   2.45  Female     No   Sat  Dinner     4
34        17.78   3.27    Male     No   Sat  Dinner     2
35        24.06   3.60    Male     No   Sat  Dinner     3
36        16.31   2.00    Male     No   Sat  Dinner     3
37        16.93   3.07  Female     No   Sat  Dinner     3
38        18.69   2.31    Male     No   Sat  Dinner     3
39        31.27   5.00    Male     No   Sat  Dinner     3
40        16.04   2.24    Male     No   Sat  Dinner     3
41        17.46   2.54    Male     No   Sun  Dinner     2
42        13.94   3.06    Male     No   Sun  Dinner     2
43         9.68   1.32    Male     No   Sun  Dinner     2
44        30.40   5.60    Male     No   Sun  Dinner     4
45        18.29   3.00    Male     No   Sun  Dinner     2
46        22.23   5.00    Male     No   Sun  Dinner     2
47        32.40   6.00    Male     No   Sun  Dinner     4
48        28.55   2.05    Male     No   Sun  Dinner     3
49        18.04   3.00    Male     No   Sun  Dinner     2
50        12.54   2.50    Male     No   Sun  Dinner     2
51        10.29   2.60  Female     No   Sun  Dinner     2
52        34.81   5.20  Female     No   Sun  Dinner     4
53         9.94   1.56    Male     No   Sun  Dinner     2
54        25.56   4.34    Male     No   Sun  Dinner     4
55        19.49   3.51    Male     No   Sun  Dinner     2
56        38.01   3.00    Male    Yes   Sat  Dinner     4
57        26.41   1.50  Female     No   Sat  Dinner     2
58        11.24   1.76    Male    Yes   Sat  Dinner     2
59        48.27   6.73    Male     No   Sat  Dinner     4
60        20.29   3.21    Male    Yes   Sat  Dinner     2
61        13.81   2.00    Male    Yes   Sat  Dinner     2
62        11.02   1.98    Male    Yes   Sat  Dinner     2
63        18.29   3.76    Male    Yes   Sat  Dinner     4
64        17.59   2.64    Male     No   Sat  Dinner     3
65        20.08   3.15    Male     No   Sat  Dinner     3
66        16.45   2.47  Female     No   Sat  Dinner     2
67         3.07   1.00  Female    Yes   Sat  Dinner     1
68 

In [5]:
dummies = pd.get_dummies(tips_df)
dummies

total_bill    tip  size  sex_Female  sex_Male  smoker_No  smoker_Yes  \
0         16.99   1.01     2           1         0          1           0   
1         10.34   1.66     3           0         1          1           0   
2         21.01   3.50     3           0         1          1           0   
3         23.68   3.31     2           0         1          1           0   
4         24.59   3.61     4           1         0          1           0   
5         25.29   4.71     4           0         1          1           0   
6          8.77   2.00     2           0         1          1           0   
7         26.88   3.12     4           0         1          1           0   
8         15.04   1.96     2           0         1          1           0   
9         14.78   3.23     2           0         1          1           0   
10        10.27   1.71     2           0         1          1           0   
11        35.26   5.00     4           1         0          1           0   
12        15.42   1.57     2           0         1          1           0   
13        18.43   3.00     4           0         1          1           0   
14        14.83   3.02     2           1         0          1           0   
15        21.58   3.92     2           0         1          1           0   
16        10.33   1.67     3           1         0          1           0   
17        16.29   3.71     3           0         1          1           0   
18        16.97   3.50     3           1         0          1           0   
19        20.65   3.35     3           0         1          1           0   
20        17.92   4.08     2           0         1          1           0   
21        20.29   2.75     2           1         0          1           0   
22        15.77   2.23     2           1         0          1           0   
23        39.42   7.58     4           0         1          1           0   
24        19.82   3.18     2           0         1          1           0   
25        17.81   2.34     4           0         1          1           0   
26        13.37   2.00     2           0         1          1           0   
27        12.69   2.00     2           0         1          1           0   
28        21.70   4.30     2           0         1          1           0   
29        19.65   3.00     2           1         0          1           0   
30         9.55   1.45     2           0         1          1           0   
31        18.35   2.50     4           0         1          1           0   
32        15.06   3.00     2           1         0          1           0   
33        20.69   2.45     4           1         0          1           0   
34        17.78   3.27     2           0         1          1           0   
35        24.06   3.60     3           0         1          1           0   
36        16.31   2.00     3           0         1          1           0   
37        16.93   3.07     3           1         0          1           0   
38        18.69   2.31     3           0         1          1           0   
39        31.27   5.00     3           0         1          1           0   
40        16.04   2.24     3           0         1          1           0   
41        17.46   2.54     2           0         1          1           0   
42        13.94   3.06     2           0         1          1           0   
43         9.68   1.32     2           0         1          1           0   
44        30.40   5.60     4           0         1          1           0   
45        18.29   3.00     2           0         1          1           0   
46        22.23   5.00     2           0         1          1           0   
47        32.40   6.00     4           0         1          1           0   
48        28.55   2.05     3           0         1          1           0   
49        18.04   3.00     2           0         1          1           0   
50        12.54   2.50     2           0         1          1           0   
5

In [6]:
dummies.shape

(244, 13)

In [7]:
x = dummies.drop("total_bill",axis = 1)
x

tip  size  sex_Female  sex_Male  smoker_No  smoker_Yes  day_Fri  \
0     1.01     2           1         0          1           0        0   
1     1.66     3           0         1          1           0        0   
2     3.50     3           0         1          1           0        0   
3     3.31     2           0         1          1           0        0   
4     3.61     4           1         0          1           0        0   
5     4.71     4           0         1          1           0        0   
6     2.00     2           0         1          1           0        0   
7     3.12     4           0         1          1           0        0   
8     1.96     2           0         1          1           0        0   
9     3.23     2           0         1          1           0        0   
10    1.71     2           0         1          1           0        0   
11    5.00     4           1         0          1           0        0   
12    1.57     2           0         1          1           0        0   
13    3.00     4           0         1          1           0        0   
14    3.02     2           1         0          1           0        0   
15    3.92     2           0         1          1           0        0   
16    1.67     3           1         0          1           0        0   
17    3.71     3           0         1          1           0        0   
18    3.50     3           1         0          1           0        0   
19    3.35     3           0         1          1           0        0   
20    4.08     2           0         1          1           0        0   
21    2.75     2           1         0          1           0        0   
22    2.23     2           1         0          1           0        0   
23    7.58     4           0         1          1           0        0   
24    3.18     2           0         1          1           0        0   
25    2.34     4           0         1          1           0        0   
26    2.00     2           0         1          1           0        0   
27    2.00     2           0         1          1           0        0   
28    4.30     2           0         1          1           0        0   
29    3.00     2           1         0          1           0        0   
30    1.45     2           0         1          1           0        0   
31    2.50     4           0         1          1           0        0   
32    3.00     2           1         0          1           0        0   
33    2.45     4           1         0          1           0        0   
34    3.27     2           0         1          1           0        0   
35    3.60     3           0         1          1           0        0   
36    2.00     3           0         1          1           0        0   
37    3.07     3           1         0          1           0        0   
38    2.31     3           0         1          1           0        0   
39    5.00     3           0         1          1           0        0   
40    2.24     3           0         1          1           0        0   
41    2.54     2           0         1          1           0        0   
42    3.06     2           0         1          1           0        0   
43    1.32     2           0         1          1           0        0   
44    5.60     4           0         1          1           0        0   
45    3.00     2           0         1          1           0        0   
46    5.00     2           0         1          1           0        0   
47    6.00     4           0         1          1           0        0   
48    2.05     3           0         1          1           0        0   
49    3.00     2           0         1          1           0        0   
50    2.50     2           0         1          1           0        0   
51    2.60     2           1         0          1           0        0   
52    5.20     4           1         0          1           0        0   
53    1.56 

# split data

In [8]:
y = dummies["total_bill"]
y

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
5      25.29
6       8.77
7      26.88
8      15.04
9      14.78
10     10.27
11     35.26
12     15.42
13     18.43
14     14.83
15     21.58
16     10.33
17     16.29
18     16.97
19     20.65
20     17.92
21     20.29
22     15.77
23     39.42
24     19.82
25     17.81
26     13.37
27     12.69
28     21.70
29     19.65
30      9.55
31     18.35
32     15.06
33     20.69
34     17.78
35     24.06
36     16.31
37     16.93
38     18.69
39     31.27
40     16.04
41     17.46
42     13.94
43      9.68
44     30.40
45     18.29
46     22.23
47     32.40
48     28.55
49     18.04
50     12.54
51     10.29
52     34.81
53      9.94
54     25.56
55     19.49
56     38.01
57     26.41
58     11.24
59     48.27
60     20.29
61     13.81
62     11.02
63     18.29
64     17.59
65     20.08
66     16.45
67      3.07
68     20.23
69     15.01
70     12.02
71     17.07
72     26.86
73     25.28
74     14.73
75     10.51
76     17.92

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.2,random_state = 51)
print("x_train shape = ",x_train.shape)
print("x_test shape = ",x_test.shape)
print("y_train shape = ",y_train.shape)
print("y_test shape = ",y_test.shape)
y_train

x_train shape =  (195, 12)
x_test shape =  (49, 12)
y_train shape =  (195,)
y_test shape =  (49,)


51     10.29
183    23.17
127    14.52
221    13.42
79     17.29
72     26.86
157    25.00
85     34.83
194    16.58
27     12.69
78     22.76
59     48.27
96     27.28
126     8.52
239    29.03
113    23.95
108    18.24
31     18.35
86     13.03
130    19.08
153    24.55
120    11.69
40     16.04
230    24.01
107    25.21
81     16.66
196    10.34
56     38.01
175    32.90
148     9.78
50     12.54
13     18.43
213    13.27
8      15.04
178     9.60
43      9.68
172     7.25
179    34.63
88     24.71
154    19.77
207    38.73
219    30.14
9      14.78
216    28.15
32     15.06
91     22.49
233    10.77
114    25.71
204    20.53
92      5.75
147    11.87
67      3.07
131    20.27
118    12.43
152    17.26
93     16.32
101    15.38
80     19.44
160    21.50
140    17.47
15     21.58
123    15.95
70     12.02
82     10.07
150    14.07
11     35.26
30      9.55
139    13.16
200    18.71
61     13.81
199    13.51
44     30.40
73     25.28
1      10.34
124    12.48
29     19.65
106    20.49

# Feature Scaling

In [10]:
from sklearn.preprocessing import StandardScaler
ssc = StandardScaler()
ssc.fit(x_train)
x_train = ssc.transform(x_train)
x_test = ssc.transform(x_test)
x_train

array([[-0.31562817, -0.58722022,  1.33630621, ..., -0.61093325,
         0.65865281, -0.65865281],
       [ 2.59353707,  1.49474238, -0.74833148, ..., -0.61093325,
         0.65865281, -0.65865281],
       [-0.76319205, -0.58722022,  1.33630621, ...,  1.63684003,
        -1.51825055,  1.51825055],
       ...,
       [-1.07648677, -0.58722022, -0.74833148, ..., -0.61093325,
        -1.51825055,  1.51825055],
       [-0.10676503, -0.58722022,  1.33630621, ..., -0.61093325,
         0.65865281, -0.65865281],
       [-1.13616196, -0.58722022,  1.33630621, ..., -0.61093325,
         0.65865281, -0.65865281]])

# Linear Regression model

In [11]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [12]:
lr.coef_

array([ 4.03652746,  3.11998685, -0.25300725,  0.25300725, -0.65461348,
        0.65461348, -0.28024447, -0.27581191, -0.48938912,  0.9751546 ,
        0.94882385, -0.94882385])

In [13]:
lr.intercept_

19.567384615384615

# Predict values and test

In [14]:
x_test[0, : ]

array([ 1.47462736,  0.45376108, -0.74833148,  0.74833148,  0.80780095,
       -0.80780095, -0.29897404,  1.41421356, -0.67470281, -0.61093325,
        0.65865281, -0.65865281])

In [15]:
lr.predict([x_test[0, : ]])

array([26.93461656])

In [16]:
lr.predict(x_test)

array([26.93461656, 15.35612321, 16.42873609, 37.95086131, 22.71920745,
       20.82484109, 15.39051602, 17.19430852, 17.64495489, 19.85774667,
       16.03830985, 16.37629309, 10.14754869, 32.07632866, 12.3954942 ,
       36.20771337, 18.83904813, 16.00866651, 16.31077177, 10.73940513,
       13.31011012, 20.5799215 , 24.47186153, 16.19967177, 13.56571218,
       16.86162647, 23.5711273 , 21.36425453, 16.96974815, 15.82657029,
       19.90702578, 16.86162647, 10.73940513, 42.22649055, 24.05132522,
       11.2813863 , 14.83293814, 19.82864121, 17.37496891, 12.71219156,
       19.86178573, 29.12714091, 16.60943198, 15.85714708, 20.41461414,
       14.68385915, 21.96645583, 17.90159704, 24.88612753])

In [17]:
y_test

39     31.27
190    15.69
203    16.40
23     39.42
35     24.06
171    15.81
97     12.03
45     18.29
115    17.31
71     17.07
193    15.48
162    16.21
0      16.99
142    41.19
235    10.07
156    48.17
232    11.61
134    18.26
89     21.16
132    11.17
10     10.27
210    30.06
4      24.59
14     14.83
146    18.64
177    14.48
186    20.90
65     20.08
209    12.76
217    11.59
90     28.97
176    17.89
145     8.35
212    48.33
7      26.88
121    13.42
237    32.83
64     17.59
42     13.94
99     12.46
104    20.92
63     18.29
58     11.24
21     20.29
173    31.85
68     20.23
19     20.65
36     16.31
238    35.83
Name: total_bill, dtype: float64

In [18]:
lr.score(x_test,y_test)

0.6531895194803712

# Ridge and Lasso Regression

In [19]:
from sklearn.linear_model import Ridge,Lasso

In [20]:
rd = Ridge()
rd.fit(x_train,y_train)
rd.score(x_test,y_test)

0.6524754634197767

In [21]:
ls = Lasso()
ls.fit(x_train,y_train)
ls.score(x_test,y_test)

0.6013889779540105

In [22]:
rd2 = Ridge(alpha = 2)
rd2.fit(x_train,y_train)
rd2.score(x_test,y_test)

0.6517621888496112

In [23]:
ls2 = Lasso(alpha = 2)
ls2.fit(x_train,y_train)
ls2.score(x_test,y_test)

0.5233793038733789

In [24]:
ls5 = Lasso(alpha = 5)
ls5.fit(x_train,y_train)
ls5.score(x_test,y_test)

0.10532512764467383

In [25]:
rd5 = Ridge(alpha = 5)
rd5.fit(x_train,y_train)
rd5.score(x_test,y_test)

0.6496232399624433

# Model Evaluation

# Root Mean Squre Error

In [26]:
y_pred = lr.predict(x_test)
y_pred

array([26.93461656, 15.35612321, 16.42873609, 37.95086131, 22.71920745,
       20.82484109, 15.39051602, 17.19430852, 17.64495489, 19.85774667,
       16.03830985, 16.37629309, 10.14754869, 32.07632866, 12.3954942 ,
       36.20771337, 18.83904813, 16.00866651, 16.31077177, 10.73940513,
       13.31011012, 20.5799215 , 24.47186153, 16.19967177, 13.56571218,
       16.86162647, 23.5711273 , 21.36425453, 16.96974815, 15.82657029,
       19.90702578, 16.86162647, 10.73940513, 42.22649055, 24.05132522,
       11.2813863 , 14.83293814, 19.82864121, 17.37496891, 12.71219156,
       19.86178573, 29.12714091, 16.60943198, 15.85714708, 20.41461414,
       14.68385915, 21.96645583, 17.90159704, 24.88612753])

In [27]:
y_test

39     31.27
190    15.69
203    16.40
23     39.42
35     24.06
171    15.81
97     12.03
45     18.29
115    17.31
71     17.07
193    15.48
162    16.21
0      16.99
142    41.19
235    10.07
156    48.17
232    11.61
134    18.26
89     21.16
132    11.17
10     10.27
210    30.06
4      24.59
14     14.83
146    18.64
177    14.48
186    20.90
65     20.08
209    12.76
217    11.59
90     28.97
176    17.89
145     8.35
212    48.33
7      26.88
121    13.42
237    32.83
64     17.59
42     13.94
99     12.46
104    20.92
63     18.29
58     11.24
21     20.29
173    31.85
68     20.23
19     20.65
36     16.31
238    35.83
Name: total_bill, dtype: float64

In [28]:
from sklearn.metrics import mean_squared_error
import numpy as np

In [29]:
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)
print("mse = ",mse)
print("rmse = ",rmse)

mse =  31.369926656885553
rmse =  5.600886238523825


# Polynomial Linear Regression - ML Model Training

In [31]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [32]:
poly_reg = PolynomialFeatures(degree = 2)
poly_reg.fit(x_train)
x_train_poly = poly_reg.transform(x_train)
x_test_poly = poly_reg.transform(x_test)

In [33]:
x_train_poly.shape,x_test_poly.shape

((195, 91), (49, 91))

In [34]:
lr = LinearRegression()
lr.fit(x_train_poly,y_train)

LinearRegression()

In [35]:
lr.score(x_test_poly,y_test)

0.4487650346031177

In [36]:
lr.predict([x_test_poly[0,:]])

array([30.28076172])

In [37]:
y_pred = lr.predict(x_test_poly)
y_pred

array([30.27929688, 26.39111328, 14.29394531, 48.13720703, 23.13525391,
       19.01269531, 15.59277344, 17.55419922, 13.66796875, 26.33935547,
       17.01269531, 16.31542969,  9.11083984, 27.24121094,  8.90917969,
       22.03027344, 17.72167969, 18.82519531, 17.12011719, 10.92089844,
       15.39257812, 23.1640625 , 23.62597656, 12.67285156, 14.18066406,
       25.73828125, 23.80761719, 20.93945312, 17.42285156, 16.87939453,
       20.91162109, 25.73828125, 10.92089844, 57.47070312, 22.14501953,
       11.70019531, 16.53417969, 18.50976562, 17.66455078, 12.13964844,
       24.68457031, 30.10009766, 17.16992188, 18.61816406, 24.43701172,
       11.91210938, 21.90966797, 15.54980469, 34.97216797])

In [38]:
y_test

39     31.27
190    15.69
203    16.40
23     39.42
35     24.06
171    15.81
97     12.03
45     18.29
115    17.31
71     17.07
193    15.48
162    16.21
0      16.99
142    41.19
235    10.07
156    48.17
232    11.61
134    18.26
89     21.16
132    11.17
10     10.27
210    30.06
4      24.59
14     14.83
146    18.64
177    14.48
186    20.90
65     20.08
209    12.76
217    11.59
90     28.97
176    17.89
145     8.35
212    48.33
7      26.88
121    13.42
237    32.83
64     17.59
42     13.94
99     12.46
104    20.92
63     18.29
58     11.24
21     20.29
173    31.85
68     20.23
19     20.65
36     16.31
238    35.83
Name: total_bill, dtype: float64

In [39]:
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)
print("mse = ",mse)
print("rmse = ",rmse)

mse =  49.86066283032165
rmse =  7.0612083123444
